package com.ipinyou.optimus.console.ad.model;


public enum StrategyBusinessError {
		NO_ERROR,
		CAMPAIGN_NOT_ACTIVED, 
		CAMPAIGN_ACTIVED,	
		STRATEGY_HAD_ACTIVED, 
		STRATEGY_HAD_STOPED, 
		STRATEGY_NOT_ACTIVED, 
		STRATEGY_ACTIVED, 
		STRATEGY_ADVSTATUS_RUNING,
		STRATEGY_ADVSTATUS_STOPED,
		ILLEGAL_ARGUMENT
}
