/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.19
 * Generated at: 2015-08-31 13:38:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>  \r\n");
      out.write("<head>  \r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery.js\"></script>  \r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">  \r\n");
      out.write("<title>Insert title here</title>  \r\n");
      out.write("<script type=\"text/javascript\">  \r\n");
      out.write("    i = 1;  \r\n");
      out.write("    j = 1;  \r\n");
      out.write("    $(document).ready(function(){  \r\n");
      out.write("          \r\n");
      out.write("        $(\"#btn_add1\").click(function(){  \r\n");
      out.write("            document.getElementById(\"newUpload1\").innerHTML+='<div id=\"div_'+i+'\"><input  name=\"file\" type=\"file\"  /><input type=\"button\" value=\"删除\"  onclick=\"del_1('+i+')\"/></div>';  \r\n");
      out.write("              i = i + 1;  \r\n");
      out.write("        });  \r\n");
      out.write("          \r\n");
      out.write("        $(\"#btn_add2\").click(function(){  \r\n");
      out.write("            document.getElementById(\"newUpload2\").innerHTML+='<div id=\"div_'+j+'\"><input  name=\"file_'+j+'\" type=\"file\"  /><input type=\"button\" value=\"删除\"  onclick=\"del_2('+j+')\"/></div>';  \r\n");
      out.write("              j = j + 1;  \r\n");
      out.write("        });  \r\n");
      out.write("    });  \r\n");
      out.write("  \r\n");
      out.write("    function del_1(o){  \r\n");
      out.write("     document.getElementById(\"newUpload1\").removeChild(document.getElementById(\"div_\"+o));  \r\n");
      out.write("    }  \r\n");
      out.write("      \r\n");
      out.write("    function del_2(o){  \r\n");
      out.write("         document.getElementById(\"newUpload2\").removeChild(document.getElementById(\"div_\"+o));  \r\n");
      out.write("    }  \r\n");
      out.write("  \r\n");
      out.write("</script>  \r\n");
      out.write("</head>  \r\n");
      out.write("<body>  \r\n");
      out.write("  \r\n");
      out.write("     <h1>springMVC字节流输入上传文件</h1>   \r\n");
      out.write("    <form name=\"userForm1\" action=\"/mj/upload\" enctype=\"multipart/form-data\" method=\"post\">  \r\n");
      out.write("        <div id=\"newUpload1\">  \r\n");
      out.write("            <input type=\"file\" name=\"file\">  \r\n");
      out.write("        </div>  \r\n");
      out.write("          \r\n");
      out.write("        <input type=\"button\" id=\"btn_add1\" value=\"增加一行\" >  \r\n");
      out.write("        <input type=\"submit\" value=\"上传\" >  \r\n");
      out.write("    </form>   \r\n");
      out.write("    <br>  \r\n");
      out.write("    <br>  \r\n");
      out.write("    <hr align=\"left\" width=\"60%\" color=\"#FF0000\" size=\"3\">  \r\n");
      out.write("    <br>  \r\n");
      out.write("    <br>  \r\n");
      out.write("     <h1>springMVC包装类上传文件</h1>   \r\n");
      out.write("    <form name=\"userForm2\" action=\"/mj/upload2\" enctype=\"multipart/form-data\" method=\"post\"\">  \r\n");
      out.write("        <div id=\"newUpload2\">  \r\n");
      out.write("            <input type=\"file\" name=\"file\">  \r\n");
      out.write("          \r\n");
      out.write("        </div>  \r\n");
      out.write("        <input type=\"button\" id=\"btn_add2\" value=\"增加一行\" >  \r\n");
      out.write("        <input type=\"submit\" value=\"上传\" >  \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("    </form> \r\n");
      out.write("     <br>  \r\n");
      out.write("    <br>  \r\n");
      out.write("     <h1>springMVC传文件</h1>   \r\n");
      out.write("    <form name=\"userForm2\" action=\"/mj/fileUpload\" enctype=\"multipart/form-data\" method=\"post\">  \r\n");
      out.write("        <div id=\"newUpload2\">  \r\n");
      out.write("            <input type=\"file\" name=\"hhh\" id=\"hhh8\"> \r\n");
      out.write("            <input type=\"text\" name=\"aa\" id=\"aa\" value=\"99\"> \r\n");
      out.write("        </div>  \r\n");
      out.write("        <input type=\"button\" id=\"btn_add2\" value=\"增加一行\" >  \r\n");
      out.write("        \r\n");
      out.write("        <input type=\"submit\" value=\"上传\" >  \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("    </form>   \r\n");
      out.write("    <form name=\"userForm3\" action=\"/mj/stest\" enctype=\"multipart/form-data\" method=\"post\">  \r\n");
      out.write("            <input type=\"text\" name=\"aa\" id=\"aa\" value=\"99\"> \r\n");
      out.write("        <input type=\"button\" id=\"btn_add2\" value=\"增加一行\" >  \r\n");
      out.write("        \r\n");
      out.write("        <input type=\"submit\" value=\"tiaojiao\" >  \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("    </form>   \r\n");
      out.write("</body>  \r\n");
      out.write("</html>  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
